//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lopushok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.MaterialInStorageHistories = new HashSet<MaterialInStorageHistory>();
            this.PossibleMaterialsSuppliers = new HashSet<PossibleMaterialsSupplier>();
            this.ProductsMaterials = new HashSet<ProductsMaterial>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int MaterialTypeId { get; set; }
        public int CountInStock { get; set; }
        public int UnitOfMeasurementId { get; set; }
        public int CountInStorage { get; set; }
        public int MinimumPossibleCount { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public decimal Cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialInStorageHistory> MaterialInStorageHistories { get; set; }
        public virtual MaterialType MaterialType { get; set; }
        public virtual UnitsOfMeasurement UnitsOfMeasurement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PossibleMaterialsSupplier> PossibleMaterialsSuppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsMaterial> ProductsMaterials { get; set; }
    }
}
