//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lopushok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.MinimumCostHistories = new HashSet<MinimumCostHistory>();
            this.ProductsMaterials = new HashSet<ProductsMaterial>();
            this.SaleHistories = new HashSet<SaleHistory>();
        }
    
        public int Id { get; set; }
        public int NumberArticle { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal MinimumCostForAgent { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> WeightWithoutBox { get; set; }
        public Nullable<decimal> WeightWithBox { get; set; }
        public Nullable<int> StandartId { get; set; }
        public int ProductTypeId { get; set; }
        public int MinimumPersonForProduction { get; set; }
        public int WorkshopId { get; set; }
        public Nullable<System.TimeSpan> TimeForProduction { get; set; }
        public Nullable<decimal> OriginalCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MinimumCostHistory> MinimumCostHistories { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Standart Standart { get; set; }
        public virtual Workshop Workshop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsMaterial> ProductsMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleHistory> SaleHistories { get; set; }
    }
}
